theme: jekyll-theme-minimal
title: CaiShawn's Portfolio
description: Hey there! I'm CaiShawn from Huanggang, near Wuhan. 👋<br>Gamer, software explorer, and lifelong tinkerer. 🎮<br>Always down to connect — feel free to reach out! 🌐
